KOBO_API_TOKEN = "5723a0f5b9b01dfda17940cd8f1701beb21b6619"
KOBO_ASSET_ID = "aqjgNoL4WiESEEfQ9Sj9DL"
KOBO_MONITORING_ASSET_ID = "aDSNfsXbXygrn8rwKog5Yd"
KOBO_MONITORING_ASSET = "dXdb36aV"
KOBO_ASSET_FORM_CODE= "s8ntxUM5"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "okothbasil45@gmail.com"
SMTP_PASSWORD = "eyym rykh nysi bopv"
APP_URL = "https://carbontally-iih6rrvvsbzzn3uu8encmz.streamlit.app/"
FIREBASE_WEB_API_KEY = "AIzaSyABhH4F6H5YL3si18SBZ288orL2TdNsIUM"


[FIREBASE_CONFIG]

type = "service_account"
project_id = "carbontally-42816"
private_key_id = "35ff9cfe71fac4f9539586d0bb93a7edb1eb4d2c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxUc5ZER/rLhDz
uYtXlaG1sezOlEz3i/iRIBBfLdKfXj0MtUMeaZ1eCyjNVvmimFp1qe5Lis3E5KiW
scDjRuOCJ1x8NbxIDUuzXxiUntsmCk8pITkMtEEL+j56PfNeseeVNL7fXxYA+J8H
4MmbQHBYPmnu5jSmg82MFWArWOD+MnO/b56njOqrPCh8MHBCscleqnVftW5BHBdT
uUvrlJB8330c6dg9sT+ZwsNtdcRh6/ioE08+4GVwElFnbD17ZEC7WWFLaOgOghhG
jaw2h9Bpfno5928I8PX5WJ4UmcctCfLOzkfHMVqgmdf4UbwyRJKO2wsKtzxp8gPh
Wut3dcixAgMBAAECggEAOJgIiQrbKh+wz2k33QNn8mrQTvqsOhIVipQ2RXqFj9Hv
IEA2JN3GmT5sjmUlFc0Uihtrb/bkR+RHHpmrG58DfAX+EbLA3ipIL/65BK5S+agu
rczpvXFGlYEQMcnWBDI53LhR908M4dB4SXZoQkHl2XRKMTKOOVs13nDwGcWrQdXm
D07zEoCbbmwqjqK5Gfu4Uk4AHCQYYA9HTtjOyW+orXd1Vy47QmjWDf//prCo+Oxs
/JWiCfNG/XnU0ElkqmJGWUCAxpFQs60PAm70S130M/D7CEwVYvd49AFqOPAL36Mc
g71/1d5ak/oqpHzkoWel7EWx51SPFNyfRaDpBHYlBQKBgQDl9Y5a56+eeV5jLpyA
LCWkPE/2VpPdC3naLhVNjnr+PayeuWfFfO3/HhS+IoTMd9WvJ1V7kzq8UnB/di81
hnm5btnj1jdHIaku2DR4HJ/FO27x7aIvTM3285007ktInDNHh0RfqI75+cmvHM/i
8GusqAhWmoqG/0BI1PBx7X/bYwKBgQDFZj5Mui1jtIufsgsMrn6z/FkSSrEvDVK+
N2XTIhED0mTH9ZWAzyFD2c7fv21FMhIzUFEpp0xnRhVsucHV3aabLjVrk3J6niFF
kkH3HG/TpCzxVB2Q6iHMOa51kVgkE1qT2AfGtyDGYHrGGBuBhoc8h3mRMKMaLI+u
OBgZcnjp2wKBgHL9BhEY1210HSmVTjadXLkyW32/rzKSIX1jG83rWD83kdDQvz42
iT/Px+mHk0Y3CggKsCkZ5v3yb0SdUV//fXCnKJdQL9YG0/WTsTD6hz31yTV6cWYb
jsZU7SBhpA2L5ex3jE4VGGGRcTN6Qc2mEQGGCJ1dq7Vzf66rpAwkCZInAoGANcI6
hTrO0bCBteQPDk0XRH0c5NZimqXOOu9rU6ybZacOu0YuiP3f2VKf/F9tqsKQIlll
QSrGq/lyLEIKf+v1S52x/rIRI0OdXA0Q2fNsoP69HpwB0U1yFuQ+ltYWYvzCVjEn
LP8CdgQga4J1Ozkf62QZv2i3gpFQL+om5gc+1rECgYBzbzwuO9SuHF20XBAb/6Ei
Dwkfs8hwrZHjP6YGo5hYG8EQbIQKntJc1igFKCPy5e4Mu+AZgIS2IogGXERq+Hry
teFnfMfhSFPj965CAWQF/bBz8f4D/u/aSyOumx/9JGjSUQ5Vob5+9D+nEe4OutK6
QBivKivXD90kWalTw7w/SQ==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@carbontally-42816.iam.gserviceaccount.com"
client_id = "110815815868868551017"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40carbontally-42816.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
